### ISSUE TITLE
登陆后只剩下拖拽上传

### ISSUE THREAD

**Issue by Jeson-H** [stormyyd/containerd-apps#12]
我登陆后过了一会马上页面就空白了，刷新也是报unencrypted，一片空白
![image](https://github.com/user-attachments/assets/b8465a12-2d53-4429-a3c0-944ebfd8d8aa)

**Comment by stormyyd** [comment]
无法复现你遇到的情况，这边新建了一个容器，登录后显示正常。

建议尝试以下几种方式看看是否能解决你的问题：

1. 使用`docker restart`重启你现有的容器；
2. 使用`docker stop`停止现有容器后，清除容器`/config`目录挂载到本地的目录，重新创建一个容器并再次测试；
3. 参考[配置 DNS | Docker — 从入门到实践](https://yeasy.gitbook.io/docker_practice/network/dns)检查Docker的DNS是否配置正确。

另外，关于你提到的“刷新也是报unencrypted”这一现象，需要额外说明的有两点：

1. 该镜像提供的网页并非一个Native Web App，本质上是一个远程桌面，所以刷新只能起到重启远程桌面客户端的作用，对于应用本身来讲没有任何其他作用，如果想重启应用，请重启容器；
2. 该unencrypted提示信息不是报错，只是用来提示本机与远程应用的连接没有通过SSL/TLS进行加密，如对加密连接有需求可以到[jlesage/docker-baseimage-gui](https://github.com/jlesage/docker-baseimage-gui)查询加密配置说明。当然，在内网家庭网络的条件下，加密连接往往是没有必要的。

**Comment by Jeson-H** [comment]
我尝试了重启容器，目前已经解决这个问题，谢谢你的回答
