### ISSUE TITLE
当前电脑用户登录密码

### ISSUE THREAD

**Issue by anoniono** [stormyyd/containerd-apps#2]
你好，请问这个密码是哪个啊？
我尝试了运行 docker 的用户的密码，说不正确。exec 进 docker 改了密码，这个也不正确。

**Comment by stormyyd** [comment]
你好，仓库里的这两个镜像应该都是没有密码的说法的，不太清楚你遇到的是什么问题。

如果可以的话，麻烦附上你所遇到的问题的相关图片。

**Comment by anoniono** [comment]
刚才又试了一下，没有那个界面了，可以正常看到115登录界面。
应该是这次更新解决了，谢谢。
