### ISSUE TITLE
可以再部署时候加入下载目录的定义吗。

### ISSUE THREAD

**Issue by liang-x-j** [stormyyd/containerd-apps#3]
用了几个百度盘程序，觉得您的是最满意的。可是再更改下载目录时候遇到了问题，不知道怎么在设置里变更到自己需要的目录。
如果方便请作者给说明下，或者指导怎么在安装时候更改。谢谢。

**Comment by stormyyd** [comment]
设置百度网盘的下载路径需要两步操作：

## 第一步：启动容器时

启动容器时需要将你想要设置的下载目录映射到容器中，这个我在README中也有提到：

![baidunetdisk-readme](https://user-images.githubusercontent.com/4938213/200112065-16585e65-4741-414e-aa54-abe5a2f72ac5.png)

例如，此处你想将文件下载到机器上的`/mnt/data/Baidunetdisk`目录下，你可以设置将该行参数设置为：`-v /mnt/data/Baidunetdisk:/mnt/Downloads`，此时，容器的`/mnt/Downloads`目录就是你机器上的`/mnt/data/Baidunetdisk`目录了。

## 第二步：在百度网盘App中设置下载路径

启动容器，打开网页，打开右上角的百度网盘设置：

![baidunetdisk-main](https://user-images.githubusercontent.com/4938213/200112215-628bba51-b730-4585-bb24-e4a5ea4998a8.png)

在弹出的窗口中选择“传输设置”，点击“下载位置”输入框旁的“浏览”按钮：

![baidunetdisk-setting](https://user-images.githubusercontent.com/4938213/200112232-248b9116-66f9-48ea-b914-9a923abb7a2e.png)

接下来参考图片完成设置即可。

![baidunetdisk-step1](https://user-images.githubusercontent.com/4938213/200112261-03e93fbc-2d16-4c23-83e1-a7584462fc9f.png)

![baidunetdisk-step2](https://user-images.githubusercontent.com/4938213/200112274-ee34156f-12f2-40a4-9912-3bda1f3f5431.png)

![baidunetdisk-step3](https://user-images.githubusercontent.com/4938213/200112315-0f96ebd3-bf4b-482d-a180-5b09836083e3.png)

这样百度网盘会将文件下载到**容器**内的`/mnt/Downloads`目录下，同时Docker会帮我们将**容器**内的`/mnt/Downloads`目录映射到**实体机**的`/mnt/data/Baidunetdisk`目录下，最终达成的效果就是百度网盘将文件下载到了实体机的`/mnt/data/Baidunetdisk`目录下。

## 扩展阅读

[Use volumes | Docker Documentation](https://docs.docker.com/storage/volumes/)
[挂载主机目录 - Docker — 从入门到实践](https://yeasy.gitbook.io/docker_practice/data_management/bind-mounts)

**Comment by liang-x-j** [comment]
感谢您的回答。我是在群晖里安装的，群晖里/mnt下面不能创建目录，然后自己在群晖DOCKER配置里指定后就好了。谢谢。您的程序很好用。
再次感谢您的回复。

**Comment by stormyyd** [comment]
好的，如果没有什么问题我就先关掉issue了。
