### ISSUE TITLE
加载错误

### ISSUE THREAD

**Issue by yuzhen1024** [stormyyd/containerd-apps#6]
![Screenshot_20231128_163334](https://github.com/stormyyd/containerd-apps/assets/47154428/a63a0cae-2053-44eb-8d8f-ae2af2655fc9)

**Comment by stormyyd** [comment]
看上去是你的网络在DNS解析时存在一些问题，尝试修改DNS试试看？

**Comment by yuzhen1024** [comment]
是，没注意到这个问题。我的docker没配置dns。
